Repository 2pai-dev/animoji, pull requests merged in 2019-10, with the labels that each got.

#40 added cursor pointer
  src/assets/style.css
Labels: need review

#64 made whole emoji-card clickable, both as closed and open, fixed padding
  src/components/cardEmoji.vue
Labels: need review

#49 Added Bakemonogatari to Anime List
  src/store/listAnime.js
Labels: need review

#74 Fix emoji card expand animation
  src/components/cardEmoji.vue
Labels: need review

#50 feat: adds penguindrum
  src/store/listAnime.js
Labels: need review

#88 Add : sakurasou no pet na kanojo
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#90 Added Initial D First Stage
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#94 add yowapedal
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#91 Add 'mirai nikki' to listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#93 added dr.stone
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#96 Corrected Boruto myanimelist link
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#99 Add Elfen Lied
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#98 Update listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#103 Added 3-gatsu no Lion
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#106 Fix anime titles (capitalization, grammar, etc.)
  src/store/listAnime.js
Labels: hacktoberfest

#110 Add Wotakoi
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#111 Added Neon Genesis Evangelion
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#114 Added Shoujo Kaumei Utena and fixed out of order Sword Art Online
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#115 help improve ui
  src/App.vue
  src/assets/style.css
  src/components/backToTop.vue
  src/components/cardContributor.vue
  src/components/cardEmoji.vue
  src/components/cardHeader.vue
  src/components/footerContent.vue
  src/views/main.vue
Labels: hacktoberfest, need-review

#107 Added Kobayashi-san Chi no Maid Dragon
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#122 Added Code Geass: Lelouch of the Rebellion
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#123 Added Terror in Resonance
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#124 Added Rurouni Kenshin anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#121 add doraemon anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#116 add vinland saga anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#125 Added Puella Magi Madoka Magica
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#126 Added Ghost in the Shell
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#127 Added Natsume Yuujinchou
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#128 Added Vampire Knight
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#129 Added Free!
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#109 Update listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#130 Added D.N.Angel
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#131 added animoji Samurai Champloo
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#133 Add Amagi Brilliant Park
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#134 Added Cowboy Bebop
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#136 Added Naruto 🦊
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#137 Added Bleach into listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#138 feat(ui-updates): updates ui, adds yu-gi-oh to list
  src/components/cardEmoji.vue
  src/components/cardHeader.vue
  src/store/listAnime.js
  src/views/main.vue
Labels: hacktoberfest, need-review

#139 Added Uchuu Kyoudai
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#142 Update animelist.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#141 Added Sabage-bu!
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#140 Adding Barakamon anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#143 Update listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#144 Update listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#149 added Eyeshield 21
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#150 Added Mugen no Juunin: Immortal
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#153 Added Ano hana
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#156 Added 3 Anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#159 Added Danganronpa
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#161 add akame ga kill
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#167 Added Serial Experiments Lain
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#168 Added K-On
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#169 Added 4 Anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#170 add K Project
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#157 This changes will make files consistent indentation and spacing.
  package.json
  src/App.vue
  src/components/backToTop.vue
  src/components/cardContributor.vue
  src/components/cardEmoji.vue
  src/components/cardHeader.vue
  src/components/footerContent.vue
  src/store/index.js
  src/store/listAnime.js
  src/views/main.vue
Labels: hacktoberfest, need-review

#171 added shingeki no bahamut
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#172 add slam dunk anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#175 added Kaichou wa Maid Sama
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#179 Added Akira
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#158 Added Black Cat
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#185 Add Fruit Basket
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#188 Added His and Her Circumstances (Kare Kano)
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#187 Add Kill la Kill
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#186 Added Interstella5555
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#184 add-city-hunter
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#173 add enen no shouboutai anime
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#182 Update listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#200 added rainbow
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#207 Yahari
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#210 Added the Anime Azumanga Daioh
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#178 updated listAnime.js
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#230 Added Kiseijuu: Sei no Kakuritsu (Parasyte -the maxim-)
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#229 Added full metal alchemist brotherhood.
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#202 Added Mayonaka no Occult Koumuin
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#233 Adding Ballroom e Youkoso. Fixing json
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#227 Added anime Trigun (1998)
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#239 💦👩♨️💦👨
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#238 Added Psycho-Pass
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#237 Add FGO Babylonia
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#247 Add Koichoco
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#246 add Shokugeki no Souma
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#264 -add anime guilty crown and Mahouka Koukou no Rettousei
  src/store/listAnime.js
Labels: hacktoberfest, need-review

#258 Added Magi Sinbad no Bouken
  src/store/listAnime.js
Labels: hacktoberfest, need-review
